name: Deploy Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deployment.yml' # This workflow file
      - 'tf-backend.yml' # CloudFormation template

env:
  AWS_REGION: 'us-east-2'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  DeployCloudFormationTemplate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TF_BACKEND_DEPLOY }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify assumed role
        shell: bash
        run: |
          echo "=== Assumed Identity ==="
          aws sts get-caller-identity
          echo "========================"

      - name: Deploy CloudFormation template
        run: |
          aws cloudformation deploy \
            --template-file ./tf-backend.yml \
            --stack-name tf-backend \
